/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package extending.java.gradle.plugin;

import groovy.lang.GroovyObject;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.internal.plugins.DslObject;
import org.gradle.api.plugins.ExtensionAware;
import org.gradle.internal.metaobject.DynamicObject;
import org.gradle.plugin.devel.GradlePluginDevelopmentExtension;

/**
 * A simple 'hello world' plugin.
 */
public class ExtendingJavaGradlePluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getPluginManager().apply("java-gradle-plugin");
        GradlePluginDevelopmentExtension extension = project.getExtensions().getByType(GradlePluginDevelopmentExtension.class);
        ((ExtensionAware)extension).getExtensions().create("pluginPortal", PluginPortalExtension.class);

        extension.getPlugins().configureEach(plugin -> {
            // ((ExtensionAware)plugin).getExtensions().create("tags", TagExtension.class);
        });
    }
}
